In [54]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd

In [55]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
charity = pd.read_csv("charity_data.csv").drop(columns=["ORGANIZATION", "INCOME_AMT"])
charity

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,STATUS,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,1,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,1,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,1,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,1,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,1,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,1,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,1,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,1,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,1,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,1,N,36500179,0

In [56]:
charity.nunique()

EIN                       34299
NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
STATUS                        2
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [57]:
# Look at NAME counts for binning
counts1 = charity['NAME'].value_counts()
charity["NAME"].value_counts()[charity["NAME"].value_counts()<2].index

Index(['ARTS SCIENCE AND TECHNOLOGY EDUCATIONAL CORPORATION OF TEHACHA',
       'UPTE-CWA RETIRED MEMBERS CHAPTER 9119',
       'WORLD PRESIDENTS ORGANIZATION INC', 'HOMELESS ANIMAL RESCUE TEAM',
       'DREAM WEAVER CHARITABLE TR',
       'FLORIDA ASSOCIATION FOR THE EDUCATION OF YOUNG CHILDREN',
       'MOTHERS HELPERS INC', 'HALLMARK COUNCIL NO 3 ROYAL AND SELECT MASTERS',
       'MANNAS HANA RIDING CENTER',
       'SOUTHERN OREGON CHAPTER OF ROBERT MORRIS ASSOCIATES GROUP',
       ...
       'PSSST', 'EASTERN OREGON WORKFORCE INVESTMENT BOARD',
       'OUR PERFECT STORM', 'RED SHOE PROJECT INC',
       'CHRISTIAN DEAF FELLOWSHIP', 'ST LOUIS SLAM WOMENS FOOTBALL',
       'AIESEC ALUMNI IBEROAMERICA CORP', 'WEALLBLEEDRED ORG INC',
       'AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI',
       'WATERHOUSE CHARITABLE TR'],
      dtype='object', length=18776)

In [59]:
# Replace in dataframe
classifications_to_replace = charity["NAME"].value_counts()[charity["NAME"].value_counts()==1].index

for cls in classifications_to_replace:
    charity['NAME'] = charity['NAME'].replace(cls,"Other")
    
# Check to make sure binning was successful
charity['NAME'].value_counts()

Other                                                                 18776
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
                                                                      ...
WASHINGTON EXPLORER SEARCH AND RESCUE                                     2
INTERNATIONAL ALLIANCE THEATRICAL STAGE EMPLOYEES & MOVING PICTURE        2
BIRTH NETWORK                                                             2
NATIONAL ASSOCIATON OF CORPORATE DIRECTORS                                2
NATIONAL SOCIETY COLONIAL DAMES XVII CENTURY                              2
Name: NAME, Length: 793, dtype: int64

In [60]:
charity["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [61]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = [9, 2, 29, 14, 15, 17]

# Replace in dataframe
for app in application_types_to_replace:
    charity['APPLICATION_TYPE'] = charity['APPLICATION_TYPE'].replace("T"+str(app),"Other")

# Check to make sure binning was successful
charity['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      180
T13         66
T12         27
T25          3
Name: APPLICATION_TYPE, dtype: int64

In [62]:
charity["USE_CASE"].value_counts()

Preservation     28095
ProductDev        5671
CommunityServ      384
Heathcare          146
Other                3
Name: USE_CASE, dtype: int64

In [63]:
classifications_to_replace = charity["USE_CASE"].value_counts()[charity["USE_CASE"].value_counts()<384].index

# Replace in dataframe
for cls in classifications_to_replace:
    charity['USE_CASE'] = charity['USE_CASE'].replace(cls,"Other")
    
# Check to make sure binning was successful
charity['USE_CASE'].value_counts()

Preservation     28095
ProductDev        5671
CommunityServ      384
Other              149
Name: USE_CASE, dtype: int64

In [64]:
charity["CLASSIFICATION"].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [65]:
charity["APPLICATION_TYPE"].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      180
T13         66
T12         27
T25          3
Name: APPLICATION_TYPE, dtype: int64

In [66]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = [9, 13, 12, 2, 29, 25, 14, 15, 17]

# Replace in dataframe
for app in application_types_to_replace:
    charity['APPLICATION_TYPE'] = charity['APPLICATION_TYPE'].replace("T"+str(app),"Other")

# Check to make sure binning was successful
charity['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [67]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
charity["CLASSIFICATION"].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [68]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
charity["CLASSIFICATION"].value_counts()[charity["CLASSIFICATION"].value_counts()>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [69]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = charity["CLASSIFICATION"].value_counts()[charity["CLASSIFICATION"].value_counts()<10].index

# Replace in dataframe
for cls in classifications_to_replace:
    charity['CLASSIFICATION'] = charity['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
charity['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Other       98
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
Name: CLASSIFICATION, dtype: int64

In [70]:
charity_dummy = pd.get_dummies(charity)
charity_dummy

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_4-H CLUBS & AFFILIATED 4-H ORGANIZATIONS,NAME_AACE INTERNATIONAL,NAME_ACADEMY OF GENERAL DENTISTRY,NAME_ACADEMY OF MANAGED CARE PHARMACY,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_ACTIVE 20-30 UNITED STATES AND CANADA,...,CLASSIFICATION_C7200,CLASSIFICATION_C8000,CLASSIFICATION_C8200,CLASSIFICATION_Other,USE_CASE_CommunityServ,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,10520599,1,5000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
1,10531628,1,108590,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
2,10547893,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
3,10553066,1,6692,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
4,10556103,1,142590,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
34295,996010315,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
34296,996012607,1,5000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
34297,996015768,1,5000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
34298,996086871,1,36500179,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0

In [71]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = charity_dummy["IS_SUCCESSFUL"].values
X = charity_dummy.drop(["IS_SUCCESSFUL"],axis=1).values
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [72]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [73]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=8
hidden_nodes_layer2=5
hidden_nodes_layer3=1
nn = tf.keras.models.Sequential()

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 8)                 6784

 dense_10 (Dense)            (None, 5)                 45

 dense_11 (Dense)            (None, 1)                 6

=================================================================
Total params: 6,835
Trainable params: 6,835
Non-trainable params: 0
_________________________________________________________________

In [74]:
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [75]:
fit_model = nn.fit(X_train_scaled, y_train, validation_split=0.15, epochs=10)

Epoch 1/10
684/684 [==============================] - 2s 3ms/step - loss: 0.5601 - accuracy: 0.7344 - val_loss: 0.4766 - val_accuracy: 0.7839
Epoch 2/10
684/684 [==============================] - 2s 2ms/step - loss: 0.4645 - accuracy: 0.7830 - val_loss: 0.4560 - val_accuracy: 0.7904
Epoch 3/10
684/684 [==============================] - 2s 2ms/step - loss: 0.4466 - accuracy: 0.7895 - val_loss: 0.4484 - val_accuracy: 0.7937
Epoch 4/10
684/684 [==============================] - 2s 2ms/step - loss: 0.4378 - accuracy: 0.7938 - val_loss: 0.4459 - val_accuracy: 0.7950
Epoch 5/10
684/684 [==============================] - 2s 2ms/step - loss: 0.4309 - accuracy: 0.7978 - val_loss: 0.4401 - val_accuracy: 0.7966
Epoch 6/10
684/684 [==============================] - 2s 2ms/step - loss: 0.4282 - accuracy: 0.7979 - val_loss: 0.4411 - val_accuracy: 0.7981
Epoch 7/10
684/684 [==============================] - 2s 2ms/step - loss: 0.4251 - accuracy: 0.7990 - val_loss: 0.4434 - val_accuracy: 0.7981
Epoch 8/10
684/684 [==============================] - 2s 2ms/step - loss: 0.4240 - accuracy: 0.7998 - val_loss: 0.4462 - val_accuracy: 0.8012
Epoch 9/10
684/684 [==============================] - 2s 3ms/step - loss: 0.4229 - accuracy: 0.7986 - val_loss: 0.4428 - val_accuracy: 0.8020
Epoch 10/10
684/684 [==============================] - 3s 5ms/step - loss: 0.4218 - accuracy: 0.7994 - val_loss: 0.4442 - val_accuracy: 0.8002

In [76]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4684 - accuracy: 0.7883 - 563ms/epoch - 2ms/step
Loss: 0.46842852234840393, Accuracy: 0.7883381843566895

In [77]:
nn.save_weights('my_model.hdf5')